# Generated by Django 5.0.7 on 2025-09-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0002_company_companydocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
