# Generated by Django 5.0.7 on 2025-09-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0004_company_created_by_company_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplequotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='fleet_app.fleetcustomer'),
        ),
    ]
