# Generated by Django 5.0.7 on 2025-09-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0006_alter_invoice_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydocument',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
