# Generated by Django 5.0.7 on 2025-09-27 05:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0007_companydocument_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('hire_contract', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_hires', to='fleet_app.rentalcompany')),
            ],
        ),
        migrations.CreateModel(
            name='FleetHireDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('no_of_period', models.IntegerField(default=0)),
                ('rate_per_period', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fleet_hire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fleet_app.fleethire')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_details', to='fleet_app.rentalcompanyvehicle')),
            ],
        ),
    ]
