# Generated by Django 5.0.7 on 2025-09-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0008_fleethire_fleethiredetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleethiredetails',
            name='no_of_period',
        ),
        migrations.AddField(
            model_name='fleethiredetails',
            name='unit',
            field=models.CharField(blank=True, choices=[('Hr', 'Hour'), ('Day', 'Day'), ('Month', 'Month')], default='Hr', max_length=10, null=True),
        ),
    ]
