# Generated by Django 5.0.7 on 2025-09-29 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0009_remove_fleethiredetails_no_of_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='is_owned',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fleetcontract',
            name='operator_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_1', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='fleetcontract',
            name='operator_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operator_2', to='fleet_app.staff'),
        ),
    ]
