# Generated by Django 5.0.7 on 2025-09-29 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0010_vehicle_is_owned_alter_fleetcontract_operator_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_app.rentalcompany'),
        ),
    ]
