# Generated by Django 5.0.7 on 2025-09-29 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0011_vehicle_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleethiredetails',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hire_details', to='fleet_app.vehicle'),
        ),
    ]
