# Generated by Django 5.0.7 on 2025-09-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0012_alter_fleethiredetails_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleethiredetails',
            name='no_of_unit',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
