# Generated by Django 5.0.7 on 2025-10-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0013_fleethiredetails_no_of_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_taxable',
            field=models.BooleanField(default=True),
        ),
    ]
