# Generated by Django 5.0.7 on 2025-10-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0014_invoice_is_taxable'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplequotationdetails',
            name='period',
            field=models.CharField(blank=True, choices=[('Hour', 'Hour'), ('Day', 'Day'), ('Month', 'Month')], default='Hour', max_length=10, null=True),
        ),
    ]
