# Generated by Django 5.0.7 on 2025-10-22 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0013_alter_ledgerposting_credit_alter_ledgerposting_debit'),
        ('fleet_app', '0015_simplequotationdetails_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoucherType', models.CharField(max_length=50)),
                ('VoucherName', models.CharField(max_length=100)),
                ('Suffix', models.CharField(blank=True, max_length=20, null=True)),
                ('Prefix', models.CharField(blank=True, max_length=20, null=True)),
                ('MinLength', models.PositiveIntegerField(default=5)),
                ('StartingNo', models.PositiveIntegerField(default=1)),
                ('isDefault', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_vouchers', to='accounts_app.ledgercreation')),
            ],
        ),
    ]
