# Generated by Django 5.0.7 on 2025-10-22 08:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0016_vouchers'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleethire',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fleethire',
            name='voucherType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voucherType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
    ]
