# Generated by Django 5.0.7 on 2025-10-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0017_fleethire_date_fleethire_vouchertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='voucherType',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
    ]
