# Generated by Django 5.0.7 on 2025-10-22 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0018_alter_invoice_vouchertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice_no',
            new_name='voucher_no',
        ),
    ]
