# Generated by Django 5.0.7 on 2025-10-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0019_rename_invoice_no_invoice_voucher_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='mode_terms_of_payment',
        ),
        migrations.AddField(
            model_name='fleethire',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('Credit', 'Credit')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('Credit', 'Credit')], default='cash', max_length=10),
        ),
    ]
