# Generated by Django 5.0.7 on 2025-10-23 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0014_ledgerposting_refvoucherno_and_more'),
        ('fleet_app', '0020_remove_invoice_mode_terms_of_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleethire',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation'),
        ),
    ]
