# Generated by Django 5.0.7 on 2025-10-23 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0014_ledgerposting_refvoucherno_and_more'),
        ('fleet_app', '0022_invoice_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleethire',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='ledger',
        ),
        migrations.AlterField(
            model_name='fleetcontract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='fleethire',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fleet_hires', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='fleetquotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fleet_quotations', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='rentalcompanyvehicle',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='simplequotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_app.ledgercreation'),
        ),
    ]
