# Generated by Django 5.0.7 on 2025-10-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0023_remove_fleethire_ledger_remove_invoice_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='IsCleared',
            field=models.BooleanField(default=False),
        ),
    ]
