# Generated by Django 5.0.7 on 2025-10-31 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0024_invoice_iscleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleethire',
            name='IsCleared',
            field=models.BooleanField(default=False),
        ),
    ]
