# Generated by Django 5.0.7 on 2025-11-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0030_paymentbilldetails_currentamount_and_more'),
        ('fleet_app', '0025_fleethire_iscleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fleetcontract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='simplequotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='accounts_app.ledgercreation'),
        ),
    ]
