# Generated by Django 5.0.7 on 2025-11-05 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0026_alter_fleetcontract_customer_alter_invoice_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_first_driver', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_second_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_second_driver', to='fleet_app.staff'),
        ),
    ]
