# Generated by Django 5.0.7 on 2025-11-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0027_alter_vehicle_vehicle_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='enable_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='enable_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='enable_signature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simplequotation',
            name='enable_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simplequotation',
            name='enable_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='simplequotation',
            name='enable_signature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timesheetdetail',
            name='enable_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timesheetdetail',
            name='enable_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timesheetdetail',
            name='enable_signature',
            field=models.BooleanField(default=True),
        ),
    ]
