# Generated by Django 5.0.7 on 2025-11-09 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0028_invoice_enable_footer_invoice_enable_header_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetdetail',
            name='enable_footer',
        ),
        migrations.RemoveField(
            model_name='timesheetdetail',
            name='enable_header',
        ),
        migrations.RemoveField(
            model_name='timesheetdetail',
            name='enable_signature',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='enable_footer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='enable_header',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='enable_signature',
            field=models.BooleanField(default=True),
        ),
    ]
