# Generated by Django 5.0.7 on 2025-11-12 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0029_remove_timesheetdetail_enable_footer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheetdetail',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
