# Generated by Django 5.0.7 on 2025-11-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0030_alter_timesheetdetail_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='duration',
            field=models.CharField(max_length=20),
        ),
    ]
