# Generated by Django 5.2.8 on 2025-11-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0031_alter_timesheet_duration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FleetContractItem',
        ),
    ]
