# Generated by Django 5.2.8 on 2025-11-26 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0032_delete_fleetcontractitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fleetcontract',
            name='auto_no',
        ),
        migrations.RemoveField(
            model_name='fleetcontract',
            name='customer_CR_no',
        ),
        migrations.RemoveField(
            model_name='fleetcontract',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='fleetcontract',
            name='operator_2',
        ),
        migrations.AddField(
            model_name='fleetcontract',
            name='voucherType',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
        migrations.AddField(
            model_name='fleetcontract',
            name='vvoucher_no',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
