# Generated by Django 5.2.8 on 2025-11-26 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0033_remove_fleetcontract_auto_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fleetcontract',
            old_name='vvoucher_no',
            new_name='voucher_no',
        ),
    ]
