# Generated by Django 5.2.8 on 2025-11-26 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0034_rename_vvoucher_no_fleetcontract_voucher_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleetcontract',
            name='vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.vehicle'),
            preserve_default=False,
        ),
    ]
