# Generated by Django 5.2.8 on 2025-11-29 14:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0035_fleetcontract_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheet',
            name='timesheet_no',
        ),
        migrations.AddField(
            model_name='timesheet',
            name='voucherType',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='voucher_no',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
