# Generated by Django 5.2.8 on 2025-11-29 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0036_remove_timesheet_timesheet_no_timesheet_vouchertype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplequotation',
            old_name='quotation_no',
            new_name='voucher_no',
        ),
        migrations.AddField(
            model_name='simplequotation',
            name='voucherType',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
    ]
