# Generated by Django 5.2.8 on 2025-11-29 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0037_rename_quotation_no_simplequotation_voucher_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplequotation',
            name='voucherType',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
    ]
