# Generated by Django 5.2.8 on 2025-12-07 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0040_alter_fleethire_grand_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='tax',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
