# Generated by Django 5.2.8 on 2025-12-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0041_alter_invoicedetails_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplequotationdetails',
            name='tax_amountg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='simplequotationdetails',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
