# Generated by Django 5.2.8 on 2025-12-17 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0042_simplequotationdetails_tax_amountg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simplequotationdetails',
            old_name='tax_amountg',
            new_name='tax_amount',
        ),
    ]
