# Generated by Django 5.2.8 on 2025-12-18 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0043_rename_tax_amountg_simplequotationdetails_tax_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoicedetails',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='tax',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='simplequotationdetails',
            name='rent',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='simplequotationdetails',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='break_hours',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='total_hours_worked',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=20),
        ),
    ]
