# Generated by Django 5.2.8 on 2025-12-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0044_alter_invoicedetails_amount_alter_invoicedetails_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
