# Generated by Django 5.2.8 on 2025-12-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0045_invoice_invoice_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplequotation',
            name='quotation_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
