# Generated by Django 5.2.8 on 2025-12-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0046_simplequotation_quotation_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplequotation',
            name='terms_and_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
