# Generated by Django 5.2.8 on 2025-12-30 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0047_simplequotation_terms_and_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplequotationdetails',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simple_quotation_details', to='fleet_app.vehicle'),
        ),
    ]
