# Generated by Django 5.2.8 on 2025-12-31 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0048_simplequotationdetails_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplequotation',
            name='terms_and_condition',
            field=models.TextField(blank=True, default='Terms & Conditions\n• Vehicle will be provided as per PDO-OPAL specifications.\n• Payment terms 60 days from the date of invoice submission.\n• Fuel for the vehicle provided by your scope.\n• Maximum working normal day 10 hours/day or 280 hrs/month additional working time will be charge as over time from total amount as per 1 hrs calculation.\n• Mobilization & Demobilization will be provided by your scope.\n• Demobilization notice give 1 month prior. Vehicle maintenance is our scope.\n\nThanking you,\n\nYours Faithfully.', null=True),
        ),
    ]
