# Generated by Django 5.2.8 on 2025-12-31 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0049_alter_simplequotation_terms_and_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
