# Generated by Django 5.2.8 on 2026-01-04 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0050_alter_document_file_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleEMI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Bank Loan, Lease Payment', max_length=255, verbose_name='EMI Title')),
                ('start_date', models.DateField(help_text='First EMI date', verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='Last EMI date', verbose_name='End Date')),
                ('reminder_day', models.IntegerField(default=5, help_text='Day of month for EMI (1-31)', verbose_name='Reminder Day of Month')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optional: Monthly EMI amount', max_digits=10, null=True, verbose_name='EMI Amount')),
                ('reminder_days_before', models.IntegerField(default=3, help_text='Show notification X days before due date', verbose_name='Remind Days Before')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emis', to='fleet_app.vehicle')),
            ],
            options={
                'verbose_name': 'Vehicle EMI',
                'verbose_name_plural': 'Vehicle EMIs',
                'ordering': ['-created_at'],
            },
        ),
    ]
