# Generated by Django 5.2.8 on 2026-01-05 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0051_vehicleemi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicleemi',
            options={},
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='reminder_day',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='reminder_days_before',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
