# Generated by Django 5.2.8 on 2026-01-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0052_alter_vehicleemi_options_alter_vehicleemi_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleemi',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
