# Generated by Django 5.2.8 on 2026-01-05 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0053_alter_vehicleemi_amount_alter_vehicleemi_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleemi',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vehicleemi',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='reminder_day',
            field=models.IntegerField(help_text='Day of the month (e.g., 7)'),
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='reminder_days_before',
            field=models.IntegerField(help_text='Days before due date to start showing warning'),
        ),
        migrations.CreateModel(
            name='EMIInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('is_paid', models.BooleanField(default=False)),
                ('emi_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fleet_app.vehicleemi')),
            ],
        ),
    ]
