# Generated by Django 5.2.8 on 2026-01-05 17:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0054_remove_vehicleemi_notes_remove_vehicleemi_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emiinstallment',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='vehicleemi',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='emiinstallment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emiinstallment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emiinstallment',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emiinstallment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vehicleemi',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicleemi',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
