# Generated by Django 5.2.8 on 2026-01-08 10:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0055_alter_emiinstallment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleethiredetails',
            name='created_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleethiredetails',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fleethiredetails',
            name='updated_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fleethiredetails',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='VehicleProfitLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Details', models.CharField(max_length=255)),
                ('Amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('InvNo', models.CharField(max_length=50)),
                ('InvAmount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('Balance', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleet_app.vehicle')),
            ],
        ),
    ]
