# Generated by Django 5.2.8 on 2026-01-10 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0046_paymentdetails_vehicle'),
        ('fleet_app', '0056_fleethiredetails_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydocument',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='fleet_app.company'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='driver_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.rentalcompany'),
        ),
        migrations.AlterField(
            model_name='emiinstallment',
            name='emi_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='fleet_app.vehicleemi'),
        ),
        migrations.AlterField(
            model_name='fleetcontract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='fleetcontract',
            name='operator_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator_1', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='fleetcontract',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='fleethire',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_hires', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='fleethiredetails',
            name='fleet_hire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='fleet_app.fleethire'),
        ),
        migrations.AlterField(
            model_name='fleethiredetails',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hire_details', to='fleet_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='fleetquotation',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_quotations', to='fleet_app.company'),
        ),
        migrations.AlterField(
            model_name='fleetquotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_quotations', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='fleetquotationitem',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fleet_quotation_items', to='fleet_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='fleetquotationitem',
            name='vehicle_quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='fleet_app.fleetquotation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='fleet_app.invoice'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='rentalcompanyvehicle',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='rentalcompanyvehicle',
            name='license_plate_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.licenseplatecode'),
        ),
        migrations.AlterField(
            model_name='rentalcompanyvehicle',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, help_text='Category of the vehicle', null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vehiclecategory'),
        ),
        migrations.AlterField(
            model_name='rentalcompanyvehicle',
            name='vehicle_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.driver'),
        ),
        migrations.AlterField(
            model_name='rentalcompanyvehicle',
            name='vehicle_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.manufacturer'),
        ),
        migrations.AlterField(
            model_name='rentalcompanyvehicle',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='repairandmaintenance',
            name='vehicle_driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_driver', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='repairandmaintenance',
            name='vehicle_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repair_maintenance', to='fleet_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='repairandmaintenanceitem',
            name='repair_and_maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='fleet_app.repairandmaintenance'),
        ),
        migrations.AlterField(
            model_name='simplequotation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='simplequotationdetails',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='fleet_app.simplequotation'),
        ),
        migrations.AlterField(
            model_name='simplequotationdetails',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simple_quotation_details', to='fleet_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='driver_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='driver_name', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='operator_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator_name', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='vehicle_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='timesheetdetail',
            name='timesheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='fleet_app.timesheet'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='license_plate_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.licenseplatecode'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vehiclemodel'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vehiclecategory'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_first_driver', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_second_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_second_driver', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='vehicleemi',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emis', to='fleet_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.manufacturer'),
        ),
        migrations.AlterField(
            model_name='vehiclemodel',
            name='vehicle_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vehiclecategory'),
        ),
        migrations.AlterField(
            model_name='vehicleprofitloss',
            name='Vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profit_losses', to='fleet_app.vehicle'),
        ),
        migrations.AlterField(
            model_name='vouchers',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_vouchers', to='accounts_app.ledgercreation'),
        ),
    ]
