# Generated by Django 5.2.8 on 2026-01-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0057_alter_companydocument_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplequotation',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
