# Generated by Django 5.2.8 on 2026-01-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0058_simplequotation_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='hire_contract_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('complex', 'Complex')], default='simple', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='lpo_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='period',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='unit_rate',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
