# Generated by Django 5.2.8 on 2026-01-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0059_invoice_hire_contract_no_invoice_invoice_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedetails',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
