# Generated by Django 5.2.8 on 2026-01-29 06:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0053_alter_paymentbillmaster_ledger_and_more'),
        ('fleet_app', '0060_invoicedetails_from_date_invoicedetails_to_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=100, unique=True)),
                ('invoice_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_taxable', models.BooleanField(default=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('Credit', 'Credit')], default='cash', max_length=10)),
                ('supplier_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('other_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_order_no', models.CharField(blank=True, max_length=255, null=True)),
                ('dated', models.CharField(blank=True, max_length=100, null=True)),
                ('grand_total', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('IsCleared', models.BooleanField(default=False)),
                ('invoice_type', models.CharField(choices=[('simple', 'Simple'), ('complex', 'Complex')], default='simple', max_length=10)),
                ('lpo_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('hire_contract_no', models.CharField(blank=True, max_length=255, null=True)),
                ('hire_contract_date', models.DateField(blank=True, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=255, null=True)),
                ('onhire_date_time', models.DateTimeField(blank=True, null=True)),
                ('site_contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('offhire_date_time', models.DateTimeField(blank=True, null=True)),
                ('enable_header', models.BooleanField(default=True)),
                ('enable_footer', models.BooleanField(default=True)),
                ('enable_signature', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_contracts', to='accounts_app.ledgercreation')),
                ('salesman', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_app.staff')),
                ('voucherType', models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryContractDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=3, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('period', models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('monthly', 'Monthly')], max_length=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('IsCleared', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('delivery_contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='fleet_app.deliverycontract')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vehicle')),
            ],
        ),
    ]
