# Generated by Django 5.2.8 on 2026-01-31 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0061_deliverycontract_deliverycontractdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='replacement_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
    ]
