# Generated by Django 5.2.8 on 2026-02-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0062_vehicle_replacement_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Free'), ('2', 'Hired'), ('3', 'Service')], default='1', max_length=10, null=True),
        ),
    ]
