# Generated by Django 5.2.8 on 2026-02-07 19:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0053_alter_paymentbillmaster_ledger_and_more'),
        ('fleet_app', '0063_vehicle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_no', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('offhire_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offhires', to='accounts_app.ledgercreation')),
                ('delivery_contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offhires', to='fleet_app.deliverycontract')),
                ('voucherType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers')),
            ],
        ),
        migrations.CreateModel(
            name='OffHireDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255)),
                ('offhire_date_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('meter_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fuel_level', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicle_condition', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=20)),
                ('tax', models.DecimalField(decimal_places=3, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('period', models.CharField(blank=True, max_length=10, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('delivery_contract_detail', models.ForeignKey(help_text='Original contract detail being offhired', on_delete=django.db.models.deletion.PROTECT, related_name='offhire_details', to='fleet_app.deliverycontractdetails')),
                ('offhire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fleet_app.offhire')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vehicle')),
            ],
        ),
    ]
