# Generated by Django 5.2.8 on 2026-02-17 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0066_alter_simplequotation_terms_and_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycontract',
            name='invoice_type',
            field=models.CharField(choices=[('simple', 'Simple'), ('complex', 'Complex')], default='complex', max_length=10),
        ),
    ]
