# Generated by Django 5.2.8 on 2026-02-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0067_alter_deliverycontract_invoice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simplequotationdetails',
            name='period',
            field=models.CharField(blank=True, choices=[('Hour', 'Hour'), ('Day', 'Day'), ('Week', 'Week'), ('Month', 'Month')], default='Hour', max_length=10, null=True),
        ),
    ]
