# Generated by Django 5.2.8 on 2026-02-22 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0070_alter_simplequotation_terms_and_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplequotation',
            name='attention',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simplequotation',
            name='attention_contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='simplequotation',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_app.staff'),
        ),
    ]
