# Generated by Django 5.2.8 on 2026-02-23 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0054_ledgercreation_cr_no'),
        ('fleet_app', '0071_simplequotation_attention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fleethire',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fleet_hires_ledger', to='accounts_app.ledgercreation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_ledger', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_customer', to='accounts_app.ledgercreation'),
        ),
    ]
