# Generated by Django 5.2.8 on 2026-02-28 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0074_alter_deliverycontract_terms_and_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycontractdetails',
            name='delivery_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fleet_app.deliverycontract'),
        ),
        migrations.AlterField(
            model_name='fleethiredetails',
            name='fleet_hire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fleet_app.fleethire'),
        ),
        migrations.AlterField(
            model_name='invoicedetails',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fleet_app.invoice'),
        ),
        migrations.AlterField(
            model_name='simplequotationdetails',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='fleet_app.simplequotation'),
        ),
    ]
