# Generated by Django 5.2.8 on 2026-03-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0075_alter_deliverycontractdetails_delivery_contract_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycontract',
            name='delivery_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
