# Generated by Django 5.2.8 on 2026-03-07 08:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0055_alter_paymentbilldetails_billmaster_and_more'),
        ('fleet_app', '0076_deliverycontract_delivery_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='POMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PO_no', models.CharField(max_length=50)),
                ('PO_date', models.DateField(default=django.utils.timezone.now)),
                ('quote_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('quote_ref_date', models.DateField(blank=True, null=True)),
                ('payment_terms1', models.CharField(blank=True, max_length=200, null=True)),
                ('payment_terms2', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('vat_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('grand_total', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.ledgercreation')),
            ],
        ),
        migrations.CreateModel(
            name='PODetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('units', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('po_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='po_details', to='fleet_app.pomaster')),
            ],
        ),
    ]
