# Generated by Django 5.2.8 on 2026-03-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0077_pomaster_podetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='pomaster',
            name='kind_attn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
