# Generated by Django 5.2.8 on 2026-03-08 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0078_pomaster_kind_attn'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vat',
            field=models.BooleanField(default=False),
        ),
    ]
