# Generated by Django 5.2.8 on 2026-03-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0081_invoicedetails_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycontractdetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverycontractdetails',
            name='vehicle_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
