# Generated by Django 6.0.1 on 2026-04-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0055_alter_paymentbilldetails_billmaster_and_more'),
        ('fleet_app', '0084_remove_vehiclemodel_customer_vehicle_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='customer',
        ),
        migrations.AddField(
            model_name='vehiclemaster',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.ledgercreation'),
        ),
    ]
