# Generated by Django 6.0.1 on 2026-04-21 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0085_remove_vehicle_customer_vehiclemaster_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemaster',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fleet_app.fleetcustomer'),
        ),
    ]
