# Generated by Django 6.0.1 on 2026-06-16 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0086_alter_vehiclemaster_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemaster',
            name='customer',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='fleet_app.fleetcustomer', verbose_name='Customer / Owner'),
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='VehicleMaster',
        ),
    ]
