# Generated by Django 6.0.1 on 2026-06-16 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0055_alter_paymentbilldetails_billmaster_and_more'),
        ('fleet_app', '0087_remove_vehiclemaster_customer_vehicle_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='accounts_app.ledgercreation', verbose_name='Customer / Owner'),
        ),
    ]
