# Generated by Django 6.0.1 on 2026-06-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0088_alter_vehicle_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='RAS_inspection_date',
            new_name='fitness_test_date',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='RAS_inspection_expiry_date',
            new_name='fitness_test_expiry_date',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='driver_assignment_date',
            new_name='insurance_expiry_date',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='hook_inspection_date',
            new_name='last_service_date',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='hook_inspection_expiry_date',
            new_name='registration_expiry_date',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='lifting_belt_inspection_date',
            new_name='registration_renewed_date',
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='lifting_belt_inspection_expiry_date',
            new_name='service_due_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='RAS_inspection_certificate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='hook_inspection_certificate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='lifting_belt_inspection_certificate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='lifting_wire_rope_inspection_certificate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='lifting_wire_rope_inspection_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='lifting_wire_rope_inspection_expiry_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rate_per_day',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rate_per_hr',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rate_per_month',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rate_per_week',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rate_per_year',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_second_driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='winch_inspection_certificate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='winch_inspection_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='winch_inspection_expiry_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='wire_rope_inspection_certificate',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='wire_rope_inspection_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='wire_rope_inspection_expiry_date',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fitness_test_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_docs/fitness/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid'), ('cng', 'CNG')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_certificate',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_docs/insurance/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_document',
            field=models.FileField(blank=True, null=True, upload_to='vehicle_docs/registration/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='service_interval_km',
            field=models.PositiveIntegerField(blank=True, help_text='e.g. 5000 (service every 5000 km)', null=True),
        ),
    ]
