# Generated by Django 6.0.1 on 2026-08-06 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0089_rename_ras_inspection_date_vehicle_fitness_test_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=30, unique=True)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('chassis_number', models.CharField(blank=True, max_length=50, null=True)),
                ('engine_number', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to='vehicle_docs/registrations/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Registration',
                'verbose_name_plural': 'Vehicle Registrations',
                'ordering': ['registration_number'],
            },
        ),
        migrations.CreateModel(
            name='VehicleVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=255)),
                ('engine_code', models.CharField(blank=True, max_length=100, null=True)),
                ('trim', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehicle Variant',
                'verbose_name_plural': 'Vehicle Variants',
                'ordering': ['variant_name'],
            },
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['manufacturer_name'], 'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['model_name'], 'verbose_name': 'Vehicle Model', 'verbose_name_plural': 'Vehicle Models'},
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='vehicle_categories',
            field=models.ManyToManyField(blank=True, related_name='manufacturers', to='fleet_app.vehiclecategory', verbose_name='Vehicle Types'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet_app.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddConstraint(
            model_name='vehiclemodel',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'model_name'), name='unique_model_per_manufacturer'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet_app.vehicleregistration', verbose_name='Vehicle Registration'),
        ),
        migrations.AddField(
            model_name='vehiclevariant',
            name='vehicle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='fleet_app.vehiclemodel'),
        ),
        migrations.AddField(
            model_name='vehicleregistration',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='fleet_app.vehiclevariant'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='fleet_app.vehiclevariant', verbose_name='Vehicle Variant'),
        ),
        migrations.AddConstraint(
            model_name='vehiclevariant',
            constraint=models.UniqueConstraint(fields=('vehicle_model', 'variant_name'), name='unique_variant_per_model'),
        ),
        migrations.AddConstraint(
            model_name='vehicleregistration',
            constraint=models.UniqueConstraint(fields=('variant', 'registration_number'), name='unique_registration_per_variant'),
        ),
    ]
