# Generated by Django 6.0.1 on 2026-08-06 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0090_vehicleregistration_vehiclevariant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='vehicle_categories',
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufacturers', to='fleet_app.vehiclecategory', verbose_name='Vehicle Type'),
        ),
    ]
