# Generated by Django 6.0.1 on 2026-08-09 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0091_remove_manufacturer_vehicle_categories_and_more'),
        ('jobcard_app', '0028_jobcardcomplaint_service_type_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='staff_members', through='jobcard_app.TechnicianSkill', to='jobcard_app.skilltag'),
        ),
    ]
