# Generated by Django 6.0.1 on 2026-08-23 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0092_staff_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicedetails',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='vehicle',
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_date', models.DateTimeField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_app.staff')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet_app.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_name', models.CharField(max_length=255)),
                ('license_plate_code', models.CharField(max_length=50)),
                ('license_plate_number', models.CharField(max_length=50)),
                ('vehicle_driver', models.CharField(max_length=255)),
                ('vehicle_category', models.CharField(max_length=255)),
                ('RC_number', models.CharField(max_length=100)),
                ('contract_no', models.CharField(max_length=100)),
                ('contract_start_date', models.CharField(max_length=50)),
                ('contract_end_date', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=255)),
                ('vehicle_image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fleet_app.fleetcustomer')),
            ],
            options={
                'verbose_name': 'Vehicle Master',
                'verbose_name_plural': 'Vehicle Masters',
                'ordering': ['vehicle_name'],
            },
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceDetails',
        ),
    ]
