# Generated by Django 5.0.7 on 2025-08-17 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
