# Generated by Django 5.0.7 on 2025-09-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_menu_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='cr_ledger',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='dr_ledger',
        ),
        migrations.AlterField(
            model_name='ledgercreation',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledgers', to='accounts_app.groups'),
        ),
    ]
