# Generated by Django 5.0.7 on 2025-09-02 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_remove_journal_cr_ledger_remove_journal_dr_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='cr_ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cr_journals', to='accounts_app.ledgercreation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journal',
            name='dr_ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dr_journals', to='accounts_app.ledgercreation'),
            preserve_default=False,
        ),
    ]
