# Generated by Django 5.0.7 on 2025-09-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_journal_cr_ledger_journal_dr_ledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpaymentitems',
            name='vat_type',
            field=models.IntegerField(choices=[(1, 'No VAT'), (2, 'Inclusive VAT (5%)'), (3, 'Exclusive VAT (5%)')], default=1),
        ),
    ]
