# Generated by Django 5.0.7 on 2025-09-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0005_localpaymentitems_vat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpaymentitems',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='localpaymentitems',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
