# Generated by Django 5.0.7 on 2025-09-14 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0006_localpaymentitems_taxable_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localpaymentitems',
            name='taxable_amount',
        ),
        migrations.RemoveField(
            model_name='localpaymentitems',
            name='vat_amount',
        ),
    ]
