# Generated by Django 5.0.7 on 2025-09-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0007_remove_localpaymentitems_taxable_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpaymentitems',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
