# Generated by Django 5.0.7 on 2025-09-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0008_localpaymentitems_vat_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subgroup',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprivilege',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
    ]
