# Generated by Django 5.0.7 on 2025-10-06 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0011_customuser_created_by_customuser_updated_by_and_more'),
        ('item_master', '0014_delete_ledgerposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('VoucherNo', models.BigIntegerField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('FY', models.IntegerField(blank=True, null=True)),
                ('IsDeleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('CostCenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.costcenter')),
                ('VoucherType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_master.vouchers')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation')),
            ],
        ),
    ]
