# Generated by Django 5.0.7 on 2025-10-23 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0013_alter_ledgerposting_credit_alter_ledgerposting_debit'),
        ('item_master', '0014_delete_ledgerposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerposting',
            name='RefVoucherNo',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ledgerposting',
            name='RefVoucherType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RefVoucherType', to='item_master.vouchers'),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='VoucherType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FleetVoucherType', to='item_master.vouchers'),
        ),
    ]
