# Generated by Django 5.0.7 on 2025-10-23 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0014_ledgerposting_refvoucherno_and_more'),
        ('fleet_app', '0023_remove_fleethire_ledger_remove_invoice_ledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerposting',
            name='VoucherType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FleetVoucherType', to='fleet_app.vouchers'),
        ),
    ]
