# Generated by Django 5.0.7 on 2025-10-24 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0015_alter_ledgerposting_vouchertype'),
        ('item_master', '0014_delete_ledgerposting'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillClearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RefVoucherNo', models.PositiveIntegerField(help_text='ID of related Invoice or Hire record')),
                ('Amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('Date', models.DateField()),
                ('PaymentMode', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=10)),
                ('ChequeNo', models.CharField(blank=True, max_length=50, null=True)),
                ('ChequeDate', models.DateField(blank=True, null=True)),
                ('ChequeStatus', models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], max_length=10, null=True)),
                ('Ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_clearances_main', to='accounts_app.ledgercreation')),
                ('Ledger2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_clearances_counter', to='accounts_app.ledgercreation')),
                ('RefVoucherType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_clearances', to='item_master.vouchers')),
            ],
        ),
    ]
