# Generated by Django 5.0.7 on 2025-10-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0016_billclearance'),
        ('fleet_app', '0023_remove_fleethire_ledger_remove_invoice_ledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billclearance',
            name='RefVoucherType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_clearances', to='fleet_app.vouchers'),
        ),
    ]
