# Generated by Django 5.0.7 on 2025-10-25 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0018_billclearance_balance_billclearance_invamount_and_more'),
        ('fleet_app', '0023_remove_fleethire_ledger_remove_invoice_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billclearance',
            name='Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Payment_Receipt', to='fleet_app.vouchers'),
            preserve_default=False,
        ),
    ]
