# Generated by Django 5.0.7 on 2025-10-25 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0019_billclearance_type'),
        ('fleet_app', '0023_remove_fleethire_ledger_remove_invoice_ledger_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentitems',
            name='ledger',
        ),
        migrations.RemoveField(
            model_name='paymentitems',
            name='payment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='reference_no',
            new_name='ChequeNo',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='date',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='VAT_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='auto_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='net_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='tax_rate',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='taxable_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='updated_on',
        ),
        migrations.AddField(
            model_name='payment',
            name='BankTransferID',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='ChequeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='Cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='IsPDC',
            field=models.BooleanField(default=False, help_text='Is Post Dated Cheque?'),
        ),
        migrations.AddField(
            model_name='payment',
            name='LedgerCr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_credit_entries', to='accounts_app.ledgercreation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='LedgerDr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payment_debit_entries', to='accounts_app.ledgercreation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='PaymentMode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='PaymentNo',
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='PaymentType',
            field=models.CharField(blank=True, choices=[('cheque', 'Cheque'), ('transfer', 'Bank Transfer'), ('upi', 'UPI')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='RefVoucherNo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='RefVoucherType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_ref_voucher_type', to='fleet_app.vouchers'),
        ),
        migrations.AddField(
            model_name='payment',
            name='Remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucherType',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='payment_voucher_type', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='voucher_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentCheque',
        ),
        migrations.DeleteModel(
            name='PaymentItems',
        ),
    ]
