# Generated by Django 5.0.7 on 2025-10-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0021_payment_created_by_payment_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billclearance',
            name='PaymentMode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank', 'Bank')], max_length=10, null=True),
        ),
    ]
