# Generated by Django 5.0.7 on 2025-10-25 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0022_alter_billclearance_paymentmode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
