# Generated by Django 5.0.7 on 2025-10-27 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0023_alter_payment_date'),
        ('fleet_app', '0024_invoice_iscleared'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptBillMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('TotalAmount', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('Remark', models.TextField(blank=True, null=True)),
                ('TrnNo', models.PositiveIntegerField(blank=True, null=True)),
                ('ChequeNo', models.CharField(blank=True, max_length=50, null=True)),
                ('ChequeDate', models.DateField(blank=True, null=True)),
                ('ChequeStatus', models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('Ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_bank', to='accounts_app.ledgercreation')),
                ('Party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_party', to='accounts_app.ledgercreation')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoucherNo', models.PositiveIntegerField()),
                ('Amount', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('VoucherType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers')),
                ('BillMaster', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app.receiptbillmaster')),
            ],
        ),
    ]
