# Generated by Django 5.0.7 on 2025-10-27 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0024_receiptbillmaster_receiptbilldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptbillmaster',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
