# Generated by Django 5.0.7 on 2025-10-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0025_alter_receiptbillmaster_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receiptbillmaster',
            old_name='Party',
            new_name='Customer',
        ),
    ]
