# Generated by Django 5.0.7 on 2025-10-28 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0026_rename_party_receiptbillmaster_customer'),
        ('fleet_app', '0024_invoice_iscleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptbilldetails',
            name='VoucherType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiptbill_voucher_type', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='receiptbillmaster',
            name='Customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_party', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='receiptbillmaster',
            name='Ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_bank', to='accounts_app.ledgercreation'),
        ),
    ]
