# Generated by Django 5.0.7 on 2025-10-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0027_alter_receiptbilldetails_vouchertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptbilldetails',
            name='BillMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.receiptbillmaster'),
        ),
    ]
