# Generated by Django 5.0.7 on 2025-10-29 08:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0028_alter_receiptbilldetails_billmaster'),
        ('fleet_app', '0024_invoice_iscleared'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBillMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=django.utils.timezone.now)),
                ('TotalAmount', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('Remark', models.TextField(blank=True, null=True)),
                ('TrnNo', models.PositiveIntegerField(blank=True, null=True)),
                ('ChequeNo', models.CharField(blank=True, max_length=50, null=True)),
                ('ChequeDate', models.DateField(blank=True, null=True)),
                ('ChequeStatus', models.CharField(blank=True, choices=[('pending', 'Pending'), ('cleared', 'Cleared'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], max_length=10, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('Ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_cash_bank', to='accounts_app.ledgercreation')),
                ('Supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_party', to='accounts_app.ledgercreation')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoucherNo', models.PositiveIntegerField()),
                ('Amount', models.DecimalField(decimal_places=6, default=0, max_digits=15)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('VoucherType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paymentbill_voucher_type', to='fleet_app.vouchers')),
                ('BillMaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.paymentbillmaster')),
            ],
        ),
    ]
