# Generated by Django 5.0.7 on 2025-11-02 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0029_paymentbillmaster_paymentbilldetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbilldetails',
            name='CurrentAmount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='receiptbilldetails',
            name='CurrentAmount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentbillmaster',
            name='Ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Payment_cash_bank', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='paymentbillmaster',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Payment_party', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='receiptbillmaster',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receipt_party', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='receiptbillmaster',
            name='Ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_bank', to='accounts_app.ledgercreation'),
        ),
    ]
