# Generated by Django 5.0.7 on 2025-11-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0030_paymentbilldetails_currentamount_and_more'),
        ('fleet_app', '0027_alter_vehicle_vehicle_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbilldetails',
            name='VoucherType',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, related_name='paymentbill_voucher_type', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='receiptbilldetails',
            name='VoucherType',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='receiptbill_voucher_type', to='fleet_app.vouchers'),
        ),
    ]
