# Generated by Django 5.0.7 on 2025-11-08 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0031_alter_paymentbilldetails_vouchertype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentbilldetails',
            old_name='VoucherType',
            new_name='voucherType',
        ),
        migrations.RenameField(
            model_name='receiptbilldetails',
            old_name='VoucherType',
            new_name='voucherType',
        ),
    ]
