# Generated by Django 5.0.7 on 2025-11-17 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0032_rename_vouchertype_paymentbilldetails_vouchertype_and_more'),
        ('fleet_app', '0031_alter_timesheet_duration'),
        ('item_master', '0014_delete_ledgerposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerposting',
            name='CostCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_master.costcenter'),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='RefVoucherType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RefVoucherType', to='item_master.vouchers'),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='VoucherType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FleetVoucherType', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.ledgercreation'),
        ),
    ]
