# Generated by Django 5.0.7 on 2025-11-18 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0033_alter_ledgerposting_costcenter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoucherNo', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('PaidTo', models.CharField(max_length=255)),
                ('IsPDC', models.BooleanField(default=False)),
                ('IsCleared', models.BooleanField(default=False)),
                ('ChequeDate', models.DateField(blank=True, null=True)),
                ('ChequeNo', models.CharField(blank=True, max_length=100, null=True)),
                ('FyId', models.IntegerField(blank=True, null=True)),
                ('Ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_master_ledger', to='accounts_app.ledgercreation')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Desc', models.TextField(blank=True, null=True)),
                ('FyId', models.IntegerField(blank=True, null=True)),
                ('Ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_detail_ledger', to='accounts_app.ledgercreation')),
                ('Payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts_app.paymentmaster')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoucherNo', models.CharField(max_length=100)),
                ('Date', models.DateField()),
                ('ReceivedFrom', models.CharField(max_length=255)),
                ('IsPDC', models.BooleanField(default=False)),
                ('IsCleared', models.BooleanField(default=False)),
                ('ChequeDate', models.DateField(blank=True, null=True)),
                ('ChequeNo', models.CharField(blank=True, max_length=100, null=True)),
                ('FyId', models.IntegerField(blank=True, null=True)),
                ('Ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_master_ledger', to='accounts_app.ledgercreation')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Desc', models.TextField(blank=True, null=True)),
                ('FyId', models.IntegerField(blank=True, null=True)),
                ('Ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_detail_ledger', to='accounts_app.ledgercreation')),
                ('Receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts_app.receiptmaster')),
            ],
        ),
    ]
