# Generated by Django 5.0.7 on 2025-11-20 06:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0034_paymentmaster_paymentdetails_receiptmaster_and_more'),
        ('fleet_app', '0031_alter_timesheet_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmaster',
            name='voucherType',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='payment_master_voucher_type', to='fleet_app.vouchers'),
        ),
        migrations.AddField(
            model_name='receiptmaster',
            name='voucherType',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_master_voucher_type', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='receiptmaster',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
