# Generated by Django 5.0.7 on 2025-11-20 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0035_paymentmaster_vouchertype_receiptmaster_vouchertype_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmaster',
            old_name='VoucherNo',
            new_name='voucher_no',
        ),
        migrations.RenameField(
            model_name='receiptmaster',
            old_name='VoucherNo',
            new_name='voucher_no',
        ),
    ]
