# Generated by Django 5.0.7 on 2025-11-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0037_paymentdetails_created_by_paymentdetails_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentbillmaster',
            name='BounceCharge',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='paymentbillmaster',
            name='IsCleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentbillmaster',
            name='IsPDC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='BounceCharge',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='receiptbillmaster',
            name='BounceCharge',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='receiptbillmaster',
            name='IsCleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptbillmaster',
            name='IsPDC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receiptmaster',
            name='BounceCharge',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
    ]
