# Generated by Django 5.0.7 on 2025-11-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0038_paymentbillmaster_bouncecharge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentbillmaster',
            name='IsCleared',
        ),
        migrations.RemoveField(
            model_name='paymentmaster',
            name='IsCleared',
        ),
        migrations.RemoveField(
            model_name='receiptbillmaster',
            name='IsCleared',
        ),
        migrations.RemoveField(
            model_name='receiptmaster',
            name='IsCleared',
        ),
        migrations.AddField(
            model_name='paymentbillmaster',
            name='Cleared',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='Cleared',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptbillmaster',
            name='Cleared',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receiptmaster',
            name='Cleared',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
