# Generated by Django 5.2.8 on 2025-11-29 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0039_remove_paymentbillmaster_iscleared_and_more'),
        ('item_master', '0014_delete_ledgerposting'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpayment',
            name='voucherType',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='item_master.vouchers'),
        ),
    ]
