# Generated by Django 5.2.8 on 2025-11-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0040_localpayment_vouchertype'),
        ('fleet_app', '0039_repairandmaintenance_vouchertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localpayment',
            name='voucherType',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
    ]
