# Generated by Django 5.2.8 on 2025-11-29 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0041_alter_localpayment_vouchertype'),
        ('fleet_app', '0039_repairandmaintenance_vouchertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerposting',
            name='RefVoucherType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RefVoucherType', to='fleet_app.vouchers'),
        ),
    ]
