# Generated by Django 5.2.8 on 2025-12-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0042_alter_ledgerposting_refvouchertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billclearance',
            name='Amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='billclearance',
            name='Balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='billclearance',
            name='InvAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='contra',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='journal',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='credit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='localpayment',
            name='VAT_amount',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='localpayment',
            name='net_amount',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='localpayment',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='localpaymentitems',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='localpaymentitems',
            name='vat_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='Amount',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='VAT_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='net_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='tax_rate',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='receiptdetails',
            name='Amount',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='receiptitems',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='receiptmaster',
            name='BounceCharge',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='receiptmaster',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
