# Generated by Django 5.2.8 on 2025-12-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0043_alter_billclearance_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbilldetails',
            name='Amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentbilldetails',
            name='CurrentAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentbillmaster',
            name='BounceCharge',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentbillmaster',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='BounceCharge',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='receiptbilldetails',
            name='Amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='receiptbilldetails',
            name='CurrentAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='receiptbillmaster',
            name='BounceCharge',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='receiptbillmaster',
            name='TotalAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
