# Generated by Django 5.2.8 on 2025-12-07 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0044_alter_paymentbilldetails_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localpayment',
            name='BounceCharge',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='localpayment',
            name='ChequeDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localpayment',
            name='ChequeNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='localpayment',
            name='Cleared',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='localpayment',
            name='IsPDC',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='localpayment',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_payment_master_ledger', to='accounts_app.ledgercreation'),
        ),
    ]
