# Generated by Django 5.2.8 on 2026-01-06 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0045_localpayment_bouncecharge_localpayment_chequedate_and_more'),
        ('fleet_app', '0055_alter_emiinstallment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='Vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_details', to='fleet_app.vehicle'),
        ),
    ]
