# Generated by Django 5.2.8 on 2026-01-10 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0046_paymentdetails_vehicle'),
        ('fleet_app', '0057_alter_companydocument_company_and_more'),
        ('item_master', '0014_delete_ledgerposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billclearance',
            name='Ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_clearances_main', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='billclearance',
            name='RefVoucherType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bill_clearances', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='billclearance',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Payment_Receipt', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='contra',
            name='cr_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contra_cr_ledger', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='contra',
            name='dr_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contra_dr_ledger', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='group',
            name='main_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='accounts_app.maingroup'),
        ),
        migrations.AlterField(
            model_name='groupunder',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.group'),
        ),
        migrations.AlterField(
            model_name='groupunder',
            name='main_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.maingroup'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='cr_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cr_journals', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='dr_ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dr_journals', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='ledgercreation',
            name='groups',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='accounts_app.groups'),
        ),
        migrations.AlterField(
            model_name='ledgercreation',
            name='sub_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledgers', to='accounts_app.subgroup'),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='CostCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.costcenter'),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='RefVoucherType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='RefVoucherType', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='VoucherType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='FleetVoucherType', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='localpayment',
            name='payment_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_payment_master_ledger', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='localpaymentcheque',
            name='localpayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='accounts_app.localpayment'),
        ),
        migrations.AlterField(
            model_name='localpaymentitems',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='localpaymentitems',
            name='localpayment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='accounts_app.localpayment'),
        ),
        migrations.AlterField(
            model_name='maingroup',
            name='nature_of_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_groups', to='accounts_app.natureofgroup'),
        ),
        migrations.AlterField(
            model_name='paymentbilldetails',
            name='BillMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app.paymentbillmaster'),
        ),
        migrations.AlterField(
            model_name='paymentbilldetails',
            name='voucherType',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, related_name='paymentbill_voucher_type', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='paymentbillmaster',
            name='Ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Payment_cash_bank', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='paymentbillmaster',
            name='Supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Payment_party', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='Ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_detail_ledger', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='Payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='accounts_app.paymentmaster'),
        ),
        migrations.AlterField(
            model_name='paymentmaster',
            name='Ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_master_ledger', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='receiptbilldetails',
            name='BillMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app.receiptbillmaster'),
        ),
        migrations.AlterField(
            model_name='receiptbilldetails',
            name='voucherType',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, related_name='receiptbill_voucher_type', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='receiptbillmaster',
            name='Customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipt_party', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='receiptbillmaster',
            name='Ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_bank', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='receiptcheque',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='accounts_app.receipt'),
        ),
        migrations.AlterField(
            model_name='receiptdetails',
            name='Ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_detail_ledger', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='receiptdetails',
            name='Receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='details', to='accounts_app.receiptmaster'),
        ),
        migrations.AlterField(
            model_name='receiptitems',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='receiptitems',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='accounts_app.receipt'),
        ),
        migrations.AlterField(
            model_name='receiptmaster',
            name='Ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_master_ledger', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='userprivilege',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app.menu'),
        ),
        migrations.AlterField(
            model_name='userprivilege',
            name='user_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts_app.userrole'),
        ),
    ]
