# Generated by Django 5.2.8 on 2026-01-16 06:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0047_alter_billclearance_ledger_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localpayment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='localpaymentitems',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
