# Generated by Django 5.2.8 on 2026-01-19 08:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0048_alter_localpayment_date_and_more'),
        ('fleet_app', '0058_simplequotation_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillWiseOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VoucherNo', models.BigIntegerField(default=0)),
                ('InvNo', models.CharField(max_length=100)),
                ('InvDate', models.DateField(default=django.utils.timezone.now)),
                ('InvAmount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('InvBalance', models.DecimalField(decimal_places=3, max_digits=12)),
                ('dr_cr', models.CharField(choices=[('DR', 'Dr'), ('CR', 'Cr')], max_length=2)),
                ('Cleared', models.CharField(blank=True, max_length=100, null=True)),
                ('IsClosed', models.BooleanField(default=False)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billwise_openings', to='accounts_app.ledgercreation')),
                ('voucherType', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers')),
            ],
            options={
                'ordering': ['InvDate'],
                'unique_together': {('ledger', 'InvNo')},
            },
        ),
    ]
