# Generated by Django 5.2.8 on 2026-01-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0049_billwiseopening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billwiseopening',
            name='VoucherNo',
        ),
    ]
