# Generated by Django 5.2.8 on 2026-01-19 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0050_remove_billwiseopening_voucherno'),
        ('fleet_app', '0058_simplequotation_remark'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billwiseopening',
            unique_together={('ledger', 'InvNo', 'voucherType')},
        ),
    ]
