# Generated by Django 5.2.8 on 2026-01-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0051_alter_billwiseopening_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billwiseopening',
            name='Cleared',
        ),
        migrations.AddField(
            model_name='billwiseopening',
            name='IsCleared',
            field=models.BooleanField(default=False),
        ),
    ]
