# Generated by Django 5.2.8 on 2026-01-20 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0052_remove_billwiseopening_cleared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbillmaster',
            name='Ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='Payment_cash_bank', to='accounts_app.ledgercreation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receiptbillmaster',
            name='Ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cash_bank', to='accounts_app.ledgercreation'),
            preserve_default=False,
        ),
    ]
