# Generated by Django 5.2.8 on 2026-02-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0053_alter_paymentbillmaster_ledger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgercreation',
            name='cr_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
