# Generated by Django 5.2.8 on 2026-02-28 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0054_ledgercreation_cr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentbilldetails',
            name='BillMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.paymentbillmaster'),
        ),
        migrations.AlterField(
            model_name='paymentdetails',
            name='Payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts_app.paymentmaster'),
        ),
        migrations.AlterField(
            model_name='receiptbilldetails',
            name='BillMaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.receiptbillmaster'),
        ),
        migrations.AlterField(
            model_name='receiptdetails',
            name='Receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='accounts_app.receiptmaster'),
        ),
    ]
