# Generated by Django 6.0.1 on 2026-07-23 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverynote',
            old_name='job_card',
            new_name='jobcard',
        ),
        migrations.RenameField(
            model_name='estimate',
            old_name='job_card',
            new_name='jobcard',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='job_card',
            new_name='jobcard',
        ),
        migrations.RenameField(
            model_name='jobcardlabour',
            old_name='job_card',
            new_name='jobcard',
        ),
        migrations.RenameField(
            model_name='jobcardpart',
            old_name='job_card',
            new_name='jobcard',
        ),
        migrations.RenameField(
            model_name='quotation',
            old_name='job_card',
            new_name='jobcard',
        ),
        migrations.RenameField(
            model_name='vehicleinspection',
            old_name='job_card',
            new_name='jobcard',
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards_advised', to='jobcard_app.workshopstaff', verbose_name='Service Advisor'),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='workshop_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards', to='jobcard_app.workshopvehicle', verbose_name='Vehicle'),
        ),
        migrations.AlterField(
            model_name='jobcardcomplaint',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='jobcard_app.workshopstaff'),
        ),
        migrations.AlterField(
            model_name='jobcardfinding',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to='jobcard_app.workshopstaff'),
        ),
    ]
