# Generated by Django 6.0.1 on 2026-07-23 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0017_alter_purchasemaster_vouchertype_and_more'),
        ('jobcard_app', '0002_rename_job_card_deliverynote_jobcard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateitem',
            name='item_ref',
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_estimate_items', to='item_master.item'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='jobcard_app.servicecategory'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
    ]
