# Generated by Django 6.0.1 on 2026-07-24 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0003_remove_estimateitem_item_ref_estimateitem_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='estimateitem',
            name='service_category',
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='item_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='description',
            field=models.CharField(max_length=300),
        ),
    ]
