# Generated by Django 6.0.1 on 2026-07-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0004_remove_estimateitem_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='warranty',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
