# Generated by Django 6.0.1 on 2026-07-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0005_estimateitem_warranty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimateitem',
            name='item_ref',
        ),
    ]
