# Generated by Django 6.0.1 on 2026-07-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0006_remove_estimateitem_item_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimateitem',
            name='item_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
