# Generated by Django 6.0.1 on 2026-07-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0007_estimateitem_item_ref'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='quotationitem',
            name='item_type',
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_ref',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='warranty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
