# Generated by Django 6.0.1 on 2026-07-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0008_alter_quotationitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationitem',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='item_type',
            field=models.CharField(choices=[('part', 'Part'), ('labour', 'Labour')], default='part', max_length=10),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='jobcard_app.workshopstaff'),
        ),
    ]
