# Generated by Django 6.0.1 on 2026-07-25 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0055_alter_paymentbilldetails_billmaster_and_more'),
        ('jobcard_app', '0009_quotationitem_hours_quotationitem_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='vin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='VIN / Chassis No'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcard_quotations', to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcard_quotations', to='jobcard_app.workshopvehicle'),
        ),
        migrations.CreateModel(
            name='QuotationComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_type', models.CharField(choices=[('customer', 'Customer Complaint'), ('technician', 'Technician Finding')], default='customer', max_length=20)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='jobcard_app.quotation')),
            ],
            options={
                'ordering': ['complaint_type', 'order'],
            },
        ),
    ]
