# Generated by Django 6.0.1 on 2026-07-26 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0010_quotation_mileage_quotation_vin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationcomplaint',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_complaints', to='jobcard_app.servicecategory'),
        ),
        migrations.AddField(
            model_name='quotationcomplaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='quotationcomplaint',
            name='type',
            field=models.CharField(choices=[('Mechanical', 'Mechanical'), ('Electrical', 'Electrical'), ('Body', 'Body'), ('AC', 'AC'), ('Other', 'Other')], default='Mechanical', max_length=20),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='jobcard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcard_quotations', to='jobcard_app.jobcard'),
        ),
    ]
