# Generated by Django 6.0.1 on 2026-07-26 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0011_quotation_complaint_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_advised', to='jobcard_app.workshopstaff'),
        ),
    ]
