# Generated by Django 6.0.1 on 2026-07-26 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0017_alter_purchasemaster_vouchertype_and_more'),
        ('jobcard_app', '0012_alter_quotation_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverypart',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_parts', to='item_master.item'),
        ),
        migrations.AlterField(
            model_name='deliverylabour',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliverylabour',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliverypart',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliverypart',
            name='rate',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='deliverypart',
            name='unit',
            field=models.CharField(blank=True, default='No', max_length=50),
        ),
    ]
