# Generated by Django 6.0.1 on 2026-07-27 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0017_alter_purchasemaster_vouchertype_and_more'),
        ('jobcard_app', '0013_deliverypart_item_alter_deliverylabour_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverypart',
            name='amount',
        ),
        migrations.AlterField(
            model_name='deliverypart',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='delivery_parts', to='item_master.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='deliverypart',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliverypart',
            name='unit',
            field=models.CharField(choices=[('No', 'No'), ('Ltr', 'Ltr'), ('Kg', 'Kg'), ('Pkt', 'Pkt'), ('Set', 'Set')], default='No', max_length=10),
        ),
    ]
