# Generated by Django 6.0.1 on 2026-07-27 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0014_remove_deliverypart_amount_alter_deliverypart_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylabour',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_labour_entries', to='jobcard_app.workshopstaff'),
        ),
    ]
