# Generated by Django 6.0.1 on 2026-07-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0015_add_technician_to_delivery_labour'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleinspection',
            name='customer_signature_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Signature Note'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='customer_signed',
            field=models.BooleanField(default=False, verbose_name='Customer Signed'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='inspection_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
