# Generated by Django 6.0.1 on 2026-07-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0016_vehicleinspection_customer_signature_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicalinspection',
            name='brake_fluid',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'N/A')], default='good', max_length=10, verbose_name='Brake Fluid Level'),
        ),
        migrations.AddField(
            model_name='mechanicalinspection',
            name='exhaust_system',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'N/A')], default='good', max_length=10, verbose_name='Exhaust System'),
        ),
        migrations.AddField(
            model_name='mechanicalinspection',
            name='steering_fluid',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'N/A')], default='good', max_length=10, verbose_name='Power Steering Fluid'),
        ),
        migrations.AddField(
            model_name='mechanicalinspection',
            name='tyre_fl',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'N/A')], default='good', max_length=10, verbose_name='Front Left Tyre'),
        ),
        migrations.AddField(
            model_name='mechanicalinspection',
            name='tyre_fr',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'N/A')], default='good', max_length=10, verbose_name='Front Right Tyre'),
        ),
        migrations.AddField(
            model_name='mechanicalinspection',
            name='tyre_rl',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'N/A')], default='good', max_length=10, verbose_name='Rear Left Tyre'),
        ),
        migrations.AddField(
            model_name='mechanicalinspection',
            name='tyre_rr',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'N/A')], default='good', max_length=10, verbose_name='Rear Right Tyre'),
        ),
        migrations.AddField(
            model_name='mechanicalinspection',
            name='tyre_spare',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'N/A')], default='good', max_length=10, verbose_name='Spare Tyre'),
        ),
        migrations.AddField(
            model_name='mechanicalinspection',
            name='washer_fluid',
            field=models.CharField(choices=[('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('na', 'N/A')], default='good', max_length=10, verbose_name='Washer Fluid Level'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver / User Name'),
        ),
        migrations.AddField(
            model_name='vehicleinspection',
            name='overall_status',
            field=models.CharField(choices=[('pass', 'Pass / Safe'), ('attention', 'Needs Attention'), ('fail', 'Failed / Unsafe')], default='pass', max_length=20, verbose_name='Overall Inspection Status'),
        ),
    ]
