# Generated by Django 6.0.1 on 2026-08-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0017_mechanicalinspection_brake_fluid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicensePlateCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'License Plate Code',
                'verbose_name_plural': 'License Plate Codes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='StaffCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='workshopstaff',
            options={},
        ),
        migrations.AlterField(
            model_name='workshopstaff',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workshopstaff',
            name='email',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='workshopstaff',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='workshopstaff',
            name='photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workshopstaff',
            name='role',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='workshopstaff',
            name='staff_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='workshopstaff',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='workshopstaff',
            name='updated_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='workshopstaff',
            table='jobcard_app_workshopstaff',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('civil_id_or_passport_no', models.CharField(max_length=50)),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Temporary', 'Temporary'), ('Contract', 'Contract')], max_length=10, null=True)),
                ('basic_salary', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('allowances', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('bank_account_no', models.CharField(blank=True, max_length=30, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('emergency_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('visa_expiry_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Resigned', 'Resigned'), ('Terminated', 'Terminated')], max_length=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('resident_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('resident_id_expiry_date', models.DateField(blank=True, null=True)),
                ('license_type', models.CharField(blank=True, choices=[('Private', 'Private'), ('Commercial', 'Commercial'), ('Heavy Vehicle', 'Heavy Vehicle'), ('Motorcycle', 'Motorcycle')], max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, max_length=50, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('staff_image', models.ImageField(blank=True, null=True, upload_to='staff_images/')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('staff_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobcard_app.staffcategory')),
            ],
        ),
    ]
