# Generated by Django 6.0.1 on 2026-08-02 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0018_licenseplatecode_staffcategory_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopstaff',
            name='role',
        ),
        migrations.AddField(
            model_name='workshopstaff',
            name='staff_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobcard_app.staffcategory'),
        ),
    ]
