# Generated by Django 6.0.1 on 2026-08-03 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0089_rename_ras_inspection_date_vehicle_fitness_test_date_and_more'),
        ('jobcard_app', '0019_remove_workshopstaff_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LicensePlateCode',
        ),
        migrations.RemoveField(
            model_name='workshopstaff',
            name='staff_category',
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcards_advised', to='fleet_app.staff', verbose_name='Service Advisor'),
        ),
        migrations.AlterField(
            model_name='jobcardfinding',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_findings', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='jobcardcomplaint',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='vehicleinspection',
            name='inspector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_done', to='fleet_app.staff', verbose_name='Inspector'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes_advised', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates_advised', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_advised', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='deliverylabour',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_labour_entries', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='advisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_advised', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='invoicelabour',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_labours', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='jobcardlabour',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labour_entries', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='estimateitem',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items', to='fleet_app.staff'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes_tech', to='fleet_app.staff'),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.DeleteModel(
            name='StaffCategory',
        ),
        migrations.DeleteModel(
            name='WorkshopStaff',
        ),
    ]
