# Generated by Django 6.0.1 on 2026-08-06 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0020_delete_licenseplatecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopvehicle',
            name='vehicle_number',
            field=models.CharField(help_text='Auto-generated: VH-00001', max_length=20, unique=True, verbose_name='Vehicle Number'),
        ),
    ]
