# Generated by Django 6.0.1 on 2026-08-06 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0091_remove_manufacturer_vehicle_categories_and_more'),
        ('jobcard_app', '0021_alter_workshopvehicle_vehicle_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopvehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_vehicles', to='fleet_app.vehiclecategory', verbose_name='Vehicle Type'),
        ),
    ]
