# Generated by Django 6.0.1 on 2026-08-07 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0091_remove_manufacturer_vehicle_categories_and_more'),
        ('jobcard_app', '0022_workshopvehicle_vehicle_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshopvehicle',
            name='make',
        ),
        migrations.RemoveField(
            model_name='workshopvehicle',
            name='model',
        ),
        migrations.AddField(
            model_name='workshopvehicle',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_vehicles', to='fleet_app.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='workshopvehicle',
            name='vehicle_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workshop_vehicles', to='fleet_app.vehiclemodel', verbose_name='Model'),
        ),
    ]
