# Generated by Django 6.0.1 on 2026-08-09 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0023_remove_workshopvehicle_make_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mileage (km)')),
                ('fuel_level', models.CharField(choices=[('empty', 'Empty'), ('1/4', '1/4'), ('1/2', '1/2'), ('3/4', '3/4'), ('full', 'Full')], default='1/2', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='jobcard_app.jobcard')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobcard_entries', to='jobcard_app.workshopvehicle')),
            ],
            options={
                'verbose_name': 'Job Card Vehicle',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('jobcard', 'vehicle'), name='unique_vehicle_per_jobcard')],
            },
        ),
    ]
