# Generated by Django 6.0.1 on 2026-08-09 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0024_jobcardvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardcomplaint',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcard_complaints', to='jobcard_app.workshopvehicle'),
        ),
        migrations.AddField(
            model_name='jobcardlabour',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcard_labours', to='jobcard_app.workshopvehicle'),
        ),
        migrations.AddField(
            model_name='jobcardpart',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcard_parts', to='jobcard_app.workshopvehicle'),
        ),
    ]
