# Generated by Django 6.0.1 on 2026-08-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0091_remove_manufacturer_vehicle_categories_and_more'),
        ('jobcard_app', '0025_jobcardcomplaint_vehicle_jobcardlabour_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Skill Tag',
                'verbose_name_plural': 'Skill Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='jobcardcomplaint',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_name', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaint_types', to='jobcard_app.servicecategory')),
                ('required_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_types', to='jobcard_app.skilltag')),
            ],
            options={
                'verbose_name': 'Complaint Type',
                'verbose_name_plural': 'Complaint Types',
                'ordering': ['category__name', 'complaint_name'],
            },
        ),
        migrations.AddField(
            model_name='jobcardcomplaint',
            name='complaint_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcard_complaints', to='jobcard_app.complainttype'),
        ),
        migrations.CreateModel(
            name='TechnicianSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_skills', to='jobcard_app.skilltag')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_skills', to='fleet_app.staff')),
            ],
            options={
                'verbose_name': 'Technician Skill',
                'verbose_name_plural': 'Technician Skills',
                'unique_together': {('technician', 'skill')},
            },
        ),
    ]
