# Generated by Django 6.0.1 on 2026-08-09 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0027_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcardcomplaint',
            name='service_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobcard_complaints', to='jobcard_app.servicetype'),
        ),
    ]
