# Generated by Django 6.0.1 on 2026-08-13 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0017_alter_purchasemaster_vouchertype_and_more'),
        ('jobcard_app', '0028_jobcardcomplaint_service_type_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicepart',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_parts', to='item_master.item', verbose_name='Item Master'),
        ),
    ]
