# Generated by Django 6.0.1 on 2026-08-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0029_invoicepart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatecomplaint',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_complaints', to='jobcard_app.workshopvehicle'),
        ),
        migrations.AddField(
            model_name='estimateitem',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_items_by_vehicle', to='jobcard_app.workshopvehicle'),
        ),
        migrations.CreateModel(
            name='EstimateVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mileage (km)')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='jobcard_app.estimate')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimate_entries', to='jobcard_app.workshopvehicle')),
            ],
            options={
                'verbose_name': 'Estimate Vehicle',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('estimate', 'vehicle'), name='unique_vehicle_per_estimate')],
            },
        ),
    ]
