# Generated by Django 6.0.1 on 2026-08-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0030_estimatecomplaint_vehicle_estimateitem_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationcomplaint',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_complaints', to='jobcard_app.workshopvehicle'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items_by_vehicle', to='jobcard_app.workshopvehicle'),
        ),
        migrations.CreateModel(
            name='QuotationVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mileage (km)')),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='jobcard_app.quotation')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_entries', to='jobcard_app.workshopvehicle')),
            ],
            options={
                'verbose_name': 'Quotation Vehicle',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('quotation', 'vehicle'), name='unique_vehicle_per_quotation')],
            },
        ),
    ]
