# Generated by Django 6.0.1 on 2026-08-14 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0092_staff_skills'),
        ('jobcard_app', '0031_quotationcomplaint_vehicle_quotationitem_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationcomplaint',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='quotationcomplaint',
            name='complaint_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_complaints', to='jobcard_app.complainttype'),
        ),
        migrations.AddField(
            model_name='quotationcomplaint',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quotationcomplaint',
            name='service_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_complaints', to='jobcard_app.servicetype'),
        ),
        migrations.AddField(
            model_name='quotationcomplaint',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_assigned_complaints', to='fleet_app.staff'),
        ),
    ]
