# Generated by Django 6.0.1 on 2026-08-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0032_quotationcomplaint_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
