# Generated by Django 6.0.1 on 2026-08-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0092_staff_skills'),
        ('jobcard_app', '0033_estimate_voucher_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='voucherType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
