# Generated by Django 6.0.1 on 2026-08-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0092_staff_skills'),
        ('jobcard_app', '0034_estimate_vouchertype_alter_estimate_estimate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='voucherType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='fleet_app.vouchers'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
