# Generated by Django 6.0.1 on 2026-08-20 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0035_invoice_vouchertype_invoice_voucher_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='jobcard_app.invoice')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobcard_app.workshopvehicle')),
            ],
        ),
    ]
