# Generated by Django 6.0.1 on 2026-08-29 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0037_accessoriesinspection_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='vehicle',
        ),
        migrations.CreateModel(
            name='DeliveryNoteVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='jobcard_app.deliverynote')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobcard_app.workshopvehicle')),
            ],
        ),
    ]
