# Generated by Django 6.0.1 on 2026-08-30 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0093_remove_invoicedetails_invoice_and_more'),
        ('jobcard_app', '0038_remove_deliverynote_vehicle_deliverynotevehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='delivery_number',
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='voucherType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='fleet_app.vouchers'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
