# Generated by Django 6.0.1 on 2026-09-01 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0039_remove_deliverynote_delivery_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverylabour',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_labours_by_vehicle', to='jobcard_app.workshopvehicle'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='jobcard_app.workshopvehicle'),
        ),
        migrations.AddField(
            model_name='deliverypart',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_parts_by_vehicle', to='jobcard_app.workshopvehicle'),
        ),
        migrations.AddField(
            model_name='deliveryservice',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_services', to='jobcard_app.workshopvehicle'),
        ),
    ]
