# Generated by Django 6.0.1 on 2026-09-02 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0040_deliverylabour_vehicle_deliverynote_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicelabour',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_labours', to='jobcard_app.workshopvehicle'),
        ),
        migrations.AddField(
            model_name='invoiceothercharge',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_other_charges', to='jobcard_app.workshopvehicle'),
        ),
        migrations.AddField(
            model_name='invoicepart',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_parts', to='jobcard_app.workshopvehicle'),
        ),
    ]
