# Generated by Django 6.0.1 on 2026-09-08 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0093_remove_invoicedetails_invoice_and_more'),
        ('jobcard_app', '0041_invoicelabour_vehicle_invoiceothercharge_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='voucherType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations_vt', to='fleet_app.vouchers'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='voucher_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
