# Generated by Django 6.0.1 on 2026-09-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobcard_app', '0042_quotation_vouchertype_quotation_voucher_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardcomplaint',
            name='type',
            field=models.CharField(blank=True, default='Mechanical', max_length=200),
        ),
        migrations.AlterField(
            model_name='quotationcomplaint',
            name='type',
            field=models.CharField(blank=True, default='Mechanical', max_length=200),
        ),
    ]
