# Generated by Django 6.0.1 on 2026-09-10 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0093_remove_invoicedetails_invoice_and_more'),
        ('jobcard_app', '0043_alter_jobcardcomplaint_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimatecomplaint',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='estimatecomplaint',
            name='category',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='estimatecomplaint',
            name='complaint_type_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_complaints', to='jobcard_app.complainttype'),
        ),
        migrations.AddField(
            model_name='estimatecomplaint',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estimatecomplaint',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_complaints', to='jobcard_app.servicecategory'),
        ),
        migrations.AddField(
            model_name='estimatecomplaint',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='estimatecomplaint',
            name='technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimate_assigned_complaints', to='fleet_app.staff'),
        ),
        migrations.AddField(
            model_name='estimatecomplaint',
            name='type',
            field=models.CharField(blank=True, default='Mechanical', max_length=200),
        ),
    ]
