# Generated by Django 5.0.7 on 2025-09-24 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_rate_from_purchase', models.BooleanField(default=False)),
                ('price_list', models.BooleanField(default=False)),
                ('billbybill', models.BooleanField(default=False)),
                ('serial_no_tracking_item', models.BooleanField(default=False)),
                ('costcenter', models.BooleanField(default=False)),
                ('show_customer_rate', models.BooleanField(default=False)),
                ('show_vendor_rate', models.BooleanField(default=False)),
                ('barcode', models.BooleanField(default=False)),
                ('expiry', models.BooleanField(default=False)),
                ('auto_prifix', models.BooleanField(default=False)),
                ('custom_prifix', models.BooleanField(default=False)),
                ('negative_stock', models.IntegerField(choices=[(1, 'Allow'), (2, 'Warning Only'), (3, 'Block')], default=1)),
                ('credit_limit', models.IntegerField(choices=[(1, 'Allow'), (2, 'Warning Only'), (3, 'Block')], default=1)),
                ('starting_barcode', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
