# Generated by Django 5.0.7 on 2025-09-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalsettings',
            old_name='auto_prifix',
            new_name='barcode_auto_prefix',
        ),
        migrations.RenameField(
            model_name='globalsettings',
            old_name='custom_prifix',
            new_name='batch_expiry',
        ),
        migrations.RemoveField(
            model_name='globalsettings',
            name='expiry',
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='barcode_custom_prefix',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
