# Generated by Django 5.2.8 on 2025-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_auto_prifix_globalsettings_barcode_auto_prefix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CurrencyName', models.CharField(max_length=50, unique=True)),
                ('Decimal', models.PositiveSmallIntegerField(default=3)),
                ('MajorSymbol', models.CharField(blank=True, max_length=10, null=True)),
                ('MinorSymbol', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
