# Generated by Django 5.2.8 on 2026-03-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet_app', '0082_deliverycontractdetails_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=50, unique=True)),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_category', models.CharField(choices=[('Machinery', 'Machinery'), ('IT Equipment', 'IT Equipment'), ('Furniture', 'Furniture'), ('Tools', 'Tools'), ('Building', 'Building'), ('Interior', 'Interior')], max_length=50)),
                ('asset_type', models.CharField(choices=[('Vehicle', 'Vehicle'), ('Equipment', 'Equipment'), ('Machine', 'Machine')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('vat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet_app.vehicle')),
            ],
        ),
    ]
