# Generated by Django 5.2.8 on 2026-03-10 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_app', '0001_initial'),
        ('item_master', '0017_alter_purchasemaster_vouchertype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmaster',
            name='unit',
        ),
        migrations.AlterField(
            model_name='assetmaster',
            name='vat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_master.tax'),
        ),
    ]
