# Generated by Django 5.2.8 on 2026-03-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0055_alter_paymentbilldetails_billmaster_and_more'),
        ('asset_app', '0002_remove_assetmaster_unit_alter_assetmaster_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmaster',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.ledgercreation'),
        ),
    ]
