# Generated by Django 5.0.7 on 2025-08-14 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='CostCenter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_master.costcenter'),
        ),
    ]
