# Generated by Django 5.0.7 on 2025-08-22 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0002_vouchers_costcenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='voucherType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_master.vouchers'),
        ),
    ]
