# Generated by Django 5.0.7 on 2025-08-22 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0003_alter_purchasemaster_vouchertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='voucherType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item_master.vouchers'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='voucherType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item_master.vouchers'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='voucher_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
