# Generated by Django 5.0.7 on 2025-08-28 04:15

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_menu_url'),
        ('item_master', '0004_alter_purchasemaster_vouchertype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasereturnvoucheritem',
            name='purchase_return_voucher',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucheritem',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucheritem',
            name='unit',
        ),
        migrations.RenameField(
            model_name='salesreturndetail',
            old_name='BatchId',
            new_name='Batch',
        ),
        migrations.RenameField(
            model_name='salesreturndetail',
            old_name='expire_date',
            new_name='EXP',
        ),
        migrations.RenameField(
            model_name='salesreturndetail',
            old_name='manufacture_date',
            new_name='MFD',
        ),
        migrations.RenameField(
            model_name='salesreturndetail',
            old_name='sales_return_voucher',
            new_name='sales_voucher',
        ),
        migrations.RenameField(
            model_name='salesreturnmaster',
            old_name='payment_terms',
            new_name='terms_and_conditions',
        ),
        migrations.RemoveField(
            model_name='salesreturndetail',
            name='Cess',
        ),
        migrations.RemoveField(
            model_name='salesreturndetail',
            name='SerialNo',
        ),
        migrations.RemoveField(
            model_name='salesreturndetail',
            name='free_quantity',
        ),
        migrations.RemoveField(
            model_name='salesreturndetail',
            name='isexp',
        ),
        migrations.RemoveField(
            model_name='salesreturndetail',
            name='profit',
        ),
        migrations.RemoveField(
            model_name='salesreturndetail',
            name='purchase_rate',
        ),
        migrations.RemoveField(
            model_name='salesreturndetail',
            name='sales_rate_percentage',
        ),
        migrations.AddField(
            model_name='salesreturndetail',
            name='BaseUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_baseunit_details', to='item_master.unit'),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='DO_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='InvoiceDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='InvoiceNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='PO_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='customer_TRN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesreturnmaster',
            name='voucherType',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='item_master.vouchers'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='BaseUnit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salesReturn_baseunit_details', to='item_master.unit'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesReturn_unit_details', to='item_master.unit'),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='barcode_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='item_net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='item_tax_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='item_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='sales_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_unit_details', to='item_master.unit'),
        ),
        migrations.AlterField(
            model_name='salesreturnmaster',
            name='cost_center',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_master.costcenter'),
        ),
        migrations.AlterField(
            model_name='salesreturnmaster',
            name='grand_total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesreturnmaster',
            name='ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='salesreturnmaster',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('Credit', 'Credit')], default='cash', max_length=10),
        ),
        migrations.AlterField(
            model_name='salesreturnmaster',
            name='total_net_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salesreturnmaster',
            name='transaction_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='salesreturnmaster',
            name='voucher_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='PurchaseReturnMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_no', models.IntegerField(blank=True, null=True, unique=True)),
                ('voucher_no', models.CharField(max_length=100, unique=True)),
                ('transaction_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Credit', 'Credit')], default='Cash', max_length=10)),
                ('VendorInvNo', models.CharField(blank=True, max_length=100, null=True)),
                ('InvoiceDate', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('total_net_value', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('grand_total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('lrNo', models.CharField(blank=True, max_length=100, null=True)),
                ('transportCompany', models.CharField(blank=True, max_length=100, null=True)),
                ('isDeleted', models.BooleanField(default=False)),
                ('Freight', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_master.costcenter')),
                ('ledger', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts_app.ledgercreation')),
                ('voucherType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='item_master.vouchers')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseReturnDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(blank=True, max_length=100, null=True)),
                ('barcode_code', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('purchase_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('item_tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('free_quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('MFD', models.DateField(blank=True, null=True)),
                ('EXP', models.DateField(blank=True, null=True)),
                ('sales_rate_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sales_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item_total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('isexp', models.BooleanField(default=False)),
                ('QtyInBaseUnit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('RateInBaseUnit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('Cess', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('SerialNo', models.CharField(blank=True, max_length=100, null=True)),
                ('Cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('BaseUnit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchaseReturn_baseunit_details', to='item_master.unit')),
                ('Batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_master.batch')),
                ('item_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_master.item')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseReturn_unit_details', to='item_master.unit')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item_master.purchasereturnmaster')),
            ],
        ),
        migrations.DeleteModel(
            name='PurchaseReturnVoucher',
        ),
        migrations.DeleteModel(
            name='PurchaseReturnVoucherItem',
        ),
    ]
