# Generated by Django 5.0.7 on 2025-09-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0005_remove_purchasereturnvoucheritem_purchase_return_voucher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcategory',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
    ]
