# Generated by Django 5.0.7 on 2025-09-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0006_itemcategory_isdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcenter',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemmanufacturer',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tax',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vouchers',
            name='isDefault',
            field=models.BooleanField(default=False),
        ),
    ]
