# Generated by Django 5.0.7 on 2025-09-18 07:56

from django.db import migrations
from item_master.defaults import DEFAULTS

def create_defaults(apps, schema_editor):
    for model_name, fields in DEFAULTS.items():
        Model = apps.get_model("item_master", model_name)
        if not Model.objects.exists():
            Model.objects.create(**fields)


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0008_costcenter_created_by_costcenter_updated_by_and_more'),
    ]

    operations = [
        migrations.RunPython(create_defaults),
    ]
