# Generated by Django 5.0.7 on 2025-09-19 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0011_customuser_created_by_customuser_updated_by_and_more'),
        ('item_master', '0010_rename_created_batch_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_master.unit'),
        ),
        migrations.AlterField(
            model_name='itemalterunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_master.unit'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='Batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.batch'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.item'),
        ),
        migrations.AlterField(
            model_name='purchasedetail',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_unit_details', to='item_master.unit'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='cost_center',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.costcenter'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='voucherType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='item_master.vouchers'),
        ),
        migrations.AlterField(
            model_name='purchasereturndetail',
            name='Batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.batch'),
        ),
        migrations.AlterField(
            model_name='purchasereturndetail',
            name='item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.item'),
        ),
        migrations.AlterField(
            model_name='purchasereturndetail',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchaseReturn_unit_details', to='item_master.unit'),
        ),
        migrations.AlterField(
            model_name='purchasereturnmaster',
            name='cost_center',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.costcenter'),
        ),
        migrations.AlterField(
            model_name='purchasereturnmaster',
            name='ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='purchasereturnmaster',
            name='voucherType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='item_master.vouchers'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='Batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.batch'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.item'),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salesReturn_unit_details', to='item_master.unit'),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='cost_center',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.costcenter'),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='voucherType',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='item_master.vouchers'),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='Batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.batch'),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='item_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.item'),
        ),
        migrations.AlterField(
            model_name='salesreturndetail',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales_unit_details', to='item_master.unit'),
        ),
        migrations.AlterField(
            model_name='salesreturnmaster',
            name='cost_center',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.costcenter'),
        ),
        migrations.AlterField(
            model_name='salesreturnmaster',
            name='ledger',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts_app.ledgercreation'),
        ),
        migrations.AlterField(
            model_name='salesreturnmaster',
            name='voucherType',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='item_master.vouchers'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='item_master.batch'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='costCenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_master.costcenter'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_master.item'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_master.unit'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='voucherType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_master.vouchers'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='destination_cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_incoming', to='item_master.costcenter'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='source_cost_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_outgoing', to='item_master.costcenter'),
        ),
        migrations.AlterField(
            model_name='stocktransfer',
            name='voucherType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='item_master.vouchers'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_master.item'),
        ),
        migrations.AlterField(
            model_name='stocktransferitem',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='item_master.unit'),
        ),
    ]
