# Generated by Django 5.0.7 on 2025-10-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0012_ledgerposting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledgerposting',
            old_name='financial_year',
            new_name='fyId',
        ),
        migrations.AddField(
            model_name='stock',
            name='fyId',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerposting',
            name='voucher_no',
            field=models.BigIntegerField(),
        ),
    ]
