# Generated by Django 5.0.7 on 2025-10-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_master', '0013_rename_financial_year_ledgerposting_fyid_stock_fyid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LedgerPosting',
        ),
    ]
