# Generated by Django 5.2.8 on 2026-02-07 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0064_offhire_offhiredetails'),
        ('item_master', '0014_delete_ledgerposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmaster',
            name='vehicle_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vehicle'),
        ),
    ]
