# Generated by Django 5.2.8 on 2026-02-28 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0074_alter_deliverycontract_terms_and_condition_and_more'),
        ('item_master', '0015_alter_salesmaster_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='voucherType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='purchasereturnmaster',
            name='voucherType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='voucherType',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='salesreturnmaster',
            name='voucherType',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='voucherType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
    ]
