# Generated by Django 5.2.8 on 2026-02-28 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet_app', '0074_alter_deliverycontract_terms_and_condition_and_more'),
        ('item_master', '0016_alter_purchasemaster_vouchertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasemaster',
            name='voucherType',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
        migrations.AlterField(
            model_name='salesmaster',
            name='voucherType',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.PROTECT, to='fleet_app.vouchers'),
        ),
    ]
