# Generated by Django 6.0.1 on 2026-08-23 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0055_alter_paymentbilldetails_billmaster_and_more'),
        ('item_master', '0017_alter_purchasemaster_vouchertype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_master_customers', to='accounts_app.ledgercreation'),
        ),
    ]
